### ISSUE TITLE
Improve GPO Table(s)

### ISSUE THREAD

**Issue by kennyparsons** [AsBuiltReport/AsBuiltReport.Microsoft.AD#128]
### Description

Currently, it's only possible to see if a GPO is linked by looking at the OU table. It would be great if any of the Informational levels (1-3) added a column (info 1) or row (info 2-3) for the linkage. 

Here is an example of info 3:
<img width="337" alt="3-missing linkage" src="https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/assets/5930491/dd9c1dd1-7116-4363-b1df-0b1a331f77a3">

I would be great if the linkage could be added as a row here. In info 1, it would be a 4th column. 

At minimum, it would we need a count of the number of targets the GPO is linked to (or a boolean: `if ($count -eq 0) ...`. This is accomplished with something like this:
```
$dom='AD.EXAMPLE.CO<'
$GPOS=(Get-GPO -Domain $dom -All)
$GPOS | ForEach-Object { $name = $_; $count= @(((Get-GPLink -Domain $dom | Where-Object DisplayName -eq $name).Target).count); Write-Output "$name,$count"}
```
The above is a quick and dirty example, but it gets the point across. 

We could expand on this for info 2-3. When this info level is used, each individual table for each GPO would include the actual targets, not just the count (or boolean). 
<img width="338" alt="desired" src="https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/assets/5930491/8f975035-3172-48d1-b1b1-578456923915">

### Before submitting

- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this change request.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/issues) before submitting this change request.

**Comment by rebelinux** [comment]
If I understood correctly,

1. You need a column in InfoLevel1 that counts the number of times the gpo is linked to an organizational unit?

2. And in InfoLevel 2/3, you need the list of OU to which the gpo is linked?

Regards,

**Comment by kennyparsons** [comment]
Correct. Thank you

**Comment by rebelinux** [comment]
![image](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/assets/1002783/0d6c710e-0d0e-4298-bdcf-cfdaadc49c0c)

**Comment by rebelinux** [comment]
![image](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/assets/1002783/a7f4b6f4-9f73-4c0a-9a09-5113d581c96d)
