### ISSUE TITLE
Invalid PS module included in module manifest

### ISSUE THREAD

**Issue by tpcarman** [AsBuiltReport/AsBuiltReport.Microsoft.AD#3]
The `ActiveDirectory` PowerShell module is not available on the PowerShell Gallery and is causing the publication of the `AsBuiltReport.Microsoft.AD` module to fail.

https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/blob/d83023f665ef23a9265b2cd36a6498b7705290a2/AsBuiltReport.Microsoft.AD.psd1#L60

**Comment by rebelinux** [comment]
!Done.

- Removed the ActiveDirectory module reference from the RequiredModule manifest.
