### ISSUE TITLE
Issues Running Windows.AD

### ISSUE THREAD

**Issue by bzirkelbach** [AsBuiltReport/AsBuiltReport.Microsoft.AD#35]
Get the following Error when i run the AsbuiltReport.Windows.AD

Please wait while the Microsoft AD As Built Report is being generated.
New-AsBuiltReport : The 'Invoke-AsBuiltReport.Microsoft.AD' command was found in the module
'AsBuiltReport.Microsoft.AD', but the module could not be loaded. For more information, run 'Import-Module
AsBuiltReport.Microsoft.AD'.
At line:1 char:1
+ New-AsBuiltReport -Report Microsoft.AD -Target DC ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

**Comment by rebelinux** [comment]
i can't reproduce your error.

can you provide more info?

Powershell version
AsBuiltReport.Microsoft.AD module version
Complete New-AsBuiltReport command

**Comment by bzirkelbach** [comment]
I was using 0.7.1 version, I used an earlier version and it works fine.


Brad Zirkelbach
Sr. Systems Engineer


On Apr 12, 2022, at 1:04 PM, Jonathan Colon ***@***.***> wrote:

﻿



CAUTION: This message originated outside of the Auditsolv email system. Do not click links, open attachments, reply or provide information to the sender unless you know the content is safe.

________________________________



i can't reproduce your error.

can you provide more info?

Powershell version
AsBuiltReport.Microsoft.AD module version
Complete New-AsBuiltReport command

**Comment by rebelinux** [comment]
Thank you, I have found the problem. A missing module.

**Comment by rebelinux** [comment]
Until version 0.7.2 is ready for release the following module install command fix this issue.

Install-Module -Name PSWriteColor

**Comment by bzirkelbach** [comment]
Thank you!


Brad Zirkelbach
Sr. Systems Engineer


On Apr 12, 2022, at 9:06 PM, Jonathan Colon ***@***.***> wrote:

﻿



CAUTION: This message originated outside of the Auditsolv email system. Do not click links, open attachments, reply or provide information to the sender unless you know the content is safe.

________________________________



Until version 0.7.2 is ready for release the following module install command fix this issue.

Install-Module -Name PSWriteColor
