### ISSUE TITLE
Group report for well-known groups  without support for international domains

### ISSUE THREAD

**Issue by BertMueller18** [AsBuiltReport/AsBuiltReport.Microsoft.AD#42]
I'm always frustrated when group reports für e.g. german active directories, contain no table values for well known groups
german: Administratoren = Administrators

Is it poosibel to get these names in the report?

possible solution:
access well known groups via SID to include international names and expand them to localized group names
e.g. in Get-AbrADDomainObject.ps1 Line 219

```powershell
$DomainSID = (get-addomain).domainsid.Value
$ForestSID
#$Groups = 'Domain Admins','Enterprise Admins','Administrators','Server Operators','DnsAdmins','Remote Desktop Users','Incoming Forest Trust Builders','Key Admins','Backup Operators','Cert Publishers','Print Operators','Account Operators','Schema Admins'

$GroupsSID = "$DomainSID-512","$DomainSID-519",'S-1-5-32-544','S-1-5-32-549',"$DomainSID-1104",'S-1-5-32-555','S-1-5-32-557',"$DomainSID-526",'S-1-5-32-551',"$DomainSID-517",'S-1-5-32-550','S-1-5-32-548',"$DomainSID-518"
$Groups = $GroupsSID | Get-ADGroup | select -ExpandProperty name
```

Thank you for this awesome reports
Bert

**Comment by rebelinux** [comment]
Nice catch, the fix will be released in v0.7.4. Feel free to continue the bug hunting.

Thanks!
