### ISSUE TITLE
Static Entry remaining in a ps1 file

### ISSUE THREAD

**Issue by Rapidhands** [AsBuiltReport/AsBuiltReport.Microsoft.AD#7]
**Describe the bug**
Static var in a .ps1 file

**To Reproduce**
1. Go to 'Get-AbrADDomain.ps1' file
2. Seach line 159'
3. Select $Domain = "Pharmax.local"
4. Replace by $Domain
5. Error Message
Cannot find an object with identity: 'pharmax.local' under: 'DC=xxx,DC=xx'.
    + CategoryInfo          : ObjectNotFound: (pharmax.local:ADDomain) [Get-ADDomain], ADIdentityNotFoundException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:Microsoft.ActiveDirectory.Management.ADIdentityNotFoundException,Microsoft.ActiveDirectory.Management. 
   Commands.GetADDomain
    + PSComputerName        : xxxx1.xxxxx.xxx

**Expected behavior**

Regards
Olivier

**Comment by rebelinux** [comment]
thanks for reporting the bug, it has been corrected in the dev branch
