### ISSUE TITLE
No GMSA exists in AD ... error

### ISSUE THREAD

**Issue by Rapidhands** [AsBuiltReport/AsBuiltReport.Microsoft.AD#8]
**Describe the bug**
No GMSA exists in AD ... error

**To Reproduce**
1. Go to ''Get-ABrADDomain.ps1" file
2. Seach line 167
3. Get-ADServiceAccount -Filter * -Server $using:DC -Properties *
VERBOSE: [ 14:33:37:649 ] [ Document ] - Collecting the Active Directory Group Managed Service Accounts from DC .
Cannot validate argument on parameter 'Server'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command 
again.
    + CategoryInfo          : InvalidData: (:) [Get-ADServiceAccount], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.ActiveDirectory.Management.Commands.GetADServiceAccount
    + PSComputerName        : xxxx.xxxx.xxx

**Expected behavior**
I'm thinking there is a missing parameter : -ErrorAction SilentlyContinu

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rebelinux** [comment]
thanks for reporting the bug, it has been corrected in the dev branch
