### ISSUE TITLE
GetCurrentDomain Error

### ISSUE THREAD

**Issue by klwood2000** [AsBuiltReport/AsBuiltReport.Microsoft.AD#87]
**Describe the bug**
I receive the following error when executing the as-built script:

New-AsBuiltReport : Exception calling "GetCurrentDomain" with "0" argument(s): "Current security context is not
associated with an Active Directory domain or forest."
At line:1 char:1
+ New-AsBuiltReport -report Microsoft.AD -target domain2.domain2.priv - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

**To Reproduce**
Windows 10 21H2 domain joined VM named desktop1.  I'm running the script from this VM.
Windows 2016 domain controller (domain2 is the servername and domain2.priv is the domain) in a 2-way trust with a second 2016 domain controller (domain1 is the servername and domain1.priv is the domain)
Used a user account (user1) that has been added to the enterprise admin security group (and removed domain user permissions) or using the domain administrator account

**Expected behavior**
I would expect it to generate a word and html report.  I have run this same script on the domain controller itself and it has had no problems generating the report.

**Screenshots**
----------------------------------------------
 <       As Built Report Configuration      >
----------------------------------------------                                                                          Would you like to save the As Built Report configuration file? (y/n): n                                                 Please wait while the Microsoft AD As Built Report is being generated.                                                  WARNING: [ 10:47:09:748 ] [ Document ] - Please refer to the AsBuiltReport.Microsoft.AD github website for more         detailed information about this project.                                                                                WARNING: [ 10:47:09:748 ] [ Document ] - Do not forget to update your report configuration file after each new release.
WARNING: [ 10:47:09:764 ] [ Document ] - Documentation: https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD
WARNING: [ 10:47:09:764 ] [ Document ] - Issues or bug reporting:
https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/issues
WARNING: [ 10:47:09:779 ] [ Document ] - AsBuiltReport.Microsoft.AD 0.7.10 is currently installed.
WARNING: [ 10:47:32:373 ] [ Document ] - Cannot index into a null array.
WARNING: [ 10:47:32:391 ] [ Document ] - Cannot index into a null array.
WARNING: [ 10:47:32:391 ] [ Document ] - Cannot index into a null array.
_**New-AsBuiltReport : Exception calling "GetCurrentDomain" with "0" argument(s): "Current security context is not
associated with an Active Directory domain or forest."**_
At line:1 char:1
+ New-AsBuiltReport -report Microsoft.AD -target domain2.domain2.priv - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

**Additional context**
This is the full script that I am running to execute the report.  I have run just the AD-Asbuilt command and it generates the same error, so I don't believe my other lines of code are affecting it. The script is writtento install all the required modules and the end generates some excel output files.  This is for a project I am working on to setup a trust between 2 domains.  A feature request I might suggest would be for the As-Built to dump out a list of users, groups, computers and what users/computers belong to what groups into the report.  These options might be better off as a flag as there could be a lot of information and some people may not be interested in such a large report.  In our case, we have to be mindful of user overlap between two non-joined domains.  If at some point in the future the end user decides to join them and migrate users, conflicts can occur, so having that information is crucial.  I have included my full script below for your info.

********************************************************************************************************************************
Write-Host "This script will perform an inventory of an active directory domain for you."
Write-Host "It must be run from the domain controller or a domain joined Windows 10 machine."
Write-Host "The user account used will need to be an Enterprise Admin for the full collection to work"
Write-Host ""
Write-Host ""
Write-Host "What type of machine are you running this from?"
Write-Host "(1) Windows 10 domain attached"
Write-Host "(2) A domain controller in the domain"
$system = Read-Host "Enter Number: "
Write-Host ""
Write-Host ""
$domain = Read-Host "Enter the domain controller FQDN: "
$username = Read-Host "Enter username to access the domain controller: "
$password = Read-Host "Enter password for the account: "
$Foldername ="c:\temp"

# Create c:\temp directory
if (Test-Path $foldername) {
    Write-Host "Folder c:\temp exists, continuing..."
}
else {
    New-Item $Foldername -ItemType Directory
    Write-Host "Folder c:\temp created successfully, continuing..."
}

if ($system -eq 1) {
# Windows 10 Host
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::TLs12
    Install-Module -Name PSPKI -Force
    Install-Module -Name PScriboCharts -Force
    Install-Module -Name AsBuiltReport.Microsoft.AD -Force
    Install-Module -Name ImportExcel -Force
    Add-WindowsCapability -online -Name 'Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0'
    Add-WindowsCapability -Online -Name 'Rsat.CertificateServices.Tools~~~~0.0.1.0'
    Add-WindowsCapability -online -Name 'Rsat.GroupPolicy.Management.Tools~~~~0.0.1.0'
    Add-WindowsCapability –online –Name 'Rsat.Dns.Tools~~~~0.0.1.0'
    Add-WindowsCapability -online -Name 'Rsat.DHCP.Tools~~~~0.0.1.0'
}
if ($system -eq 2) {
# Domain Controller Host
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    [Net.ServicePointManager]::SecurityProtocol
    Install-PackageProvider -Name Nuget -MinimumVersion 2.8.5.201 -Force
    Install-Module -Name ImportExcel -Force
    Install-Module -Name PSPKI -Force
    Install-Module -Name PScriboCharts -Force
    Install-Module -Name AsBuiltReport.Microsoft.AD -Force
    Install-WindowsFeature -Name RSAT-ADCS
    Enable-WindowsOptionalFeature -FeatureName RSAT-AD-PowerShell
    Enable-WindowsOptionalFeature -FeatureName RSAT-ADCS,RSAT-ADCS-mgmt
    Enable-WindowsOptionalFeature -FeatureName RSAT-DNS-Server
    Enable-WindowsOptionalFeature -FeatureName RSAT-DHCP
    Enable-WindowsOptionalFeature -FeatureName GPMC
}

# As-Built Script Execution
New-AsBuiltReport -Report Microsoft.AD -Target $domain -Username $username -Password $password -Format Html,Word -OutputFolderPath $foldername -Timestamp -EnableHealthCheck

# Get Domain Attached Computer List
get-adcomputer -filter * -Properties * | export-excel -path $foldername\computerexport.xlsx

# Get Domain User List
get-aduser -filter * -Properties * | Select-Object Name, Surname, GivenName, SamAccountName, CanonicalName, DistinguishedName | export-excel -path $foldername\userexport.xlsx

# Get Domain Group Info
get-adgroup -filter * -Properties * | export-excel -path $foldername\groupexport.xlsx

# Get Group Name
get-adgroup -filter * | select-object Name | export-csv -path $foldername\grouplist.csv

# Get group membership
import-csv $foldername\grouplist.csv | Foreach-object {
    Get-ADGroupMember -Identity $($_.Name) | Select-Object Name, ObjectClass, SAMaccountName | export-excel -path $foldername\"Group.xlsx" -Append -Worksheet $($_.Name)
}

**Comment by rebelinux** [comment]
Hello:

Can you run this code in a powershell console from the computer desktop1?

`[DirectoryServices.ActiveDirectory.Domain]::GetCurrentDomain()`

in my homelab it show the following output:

```
PS C:\Users\jocolon> [DirectoryServices.ActiveDirectory.Domain]::GetCurrentDomain()

Forest                  : pharmax.local
DomainControllers       : {Server-DC-01V.pharmax.local, cayey-dc-01v.pharmax.local}
Children                : {acad.pharmax.local}
DomainMode              : Unknown
DomainModeLevel         : 7
Parent                  :
PdcRoleOwner            : Server-DC-01V.pharmax.local
RidRoleOwner            : Server-DC-01V.pharmax.local
InfrastructureRoleOwner : Server-DC-01V.pharmax.local
Name                    : pharmax.local

PS C:\Users\jocolon>
```

The error "Current security context is not associated with an Active Directory domain or forest." is related to permissions or if the user is not part of the AD domain deployed on the network.

Also can you generate a 'New-AsBuiltReportConfig' configuration file and try to disable the CA section?

https://github.com/rebelinux/AsBuiltReport.Microsoft.AD#pencil2-configuration

![Screenshot from 2022-11-02 12-29-26](https://user-images.githubusercontent.com/1002783/199546798-72e31dbd-3717-4650-a0e1-75875e87d1db.png)

Generate a Microsoft Active Directory As Built Report for Domain Controller Server 'admin-dc-01v.contoso.local' using specified credentials and report configuration file. Export report to Text, HTML & DOCX formats. Use default report style. Save reports to 'C:\Users\Jon\Documents'. Display verbose messages to the console.

`PS C:\> New-AsBuiltReport -Report Microsoft.AD -Target 'admin-dc-01v.contoso.local' -Username 'administrator@contoso.local' -Password 'P@ssw0rd' -Format Text,Html,Word -OutputFolderPath 'C:\Users\Jon\Documents' -ReportConfigFilePath 'C:\Users\Jon\AsBuiltReport\AsBuiltReport.Microsoft.AD.json' -Verbose`

**Comment by klwood2000** [comment]
Jonathan,

Thanks for the quick response.  I think I figured out the issue.

First off, I tried the command you gave me and that worked correctly for
both the Administrator and the user account from the Windows 10 Workstation.

Where I think the error was from was the way in which I was enabling
features in Windows.  I was using enable-windowsoptionalfeature instead of
install-windowsfeature.  I think this was preventing the packages from
being installed and the script was failing because of it.  Once I changed
the command, the script executed correctly.

I appreciate the assistance!

Thank you,
Kevin Wood

**Comment by rebelinux** [comment]
Now I am confused because this part of the report is intended to not allow it to run if the modules and features are not currently installed.

```
    #Validate Required Modules and Features
    $OSType = (Get-ComputerInfo).OsProductType
    if ($OSType -eq 'WorkStation') {
        Get-RequiredFeature -Name 'Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0' -OSType $OSType
        Get-RequiredFeature -Name 'Rsat.CertificateServices.Tools~~~~0.0.1.0' -OSType $OSType
        Get-RequiredFeature -Name 'Rsat.GroupPolicy.Management.Tools~~~~0.0.1.0' -OSType $OSType
        Get-RequiredFeature -Name 'Rsat.Dns.Tools~~~~0.0.1.0' -OSType $OSType
        Get-RequiredFeature -Name 'Rsat.DHCP.Tools~~~~0.0.1.0' -OSType $OSType

    }
    if ($OSType -eq 'Server' -or $OSType -eq 'DomainController') {
        Get-RequiredFeature -Name RSAT-AD-PowerShell -OSType $OSType
        Get-RequiredFeature -Name RSAT-ADCS -OSType $OSType
        Get-RequiredFeature -Name RSAT-ADCS-mgmt -OSType $OSType
        Get-RequiredFeature -Name RSAT-DNS-Server -OSType $OSType
        Get-RequiredFeature -Name RSAT-DHCP -OSType $OSType
        Get-RequiredFeature -Name GPMC -OSType $OSType
    }

    Get-RequiredModule -Name PSPKI -Version '3.7.2'
```

I will be doing more tests in this matter.

Thanks!
