### ISSUE TITLE
DHCP Report without domain controller / domain admin access.

### ISSUE THREAD

**Issue by dyde121** [AsBuiltReport/AsBuiltReport.Microsoft.AD#90]
### Description

It would be useful to have an option to run a report for only DHCP.

In this scenario, DHCP is on a separate server (not installed on a DC)
User running report has Administrator access on DHCP server, but no domain admin credentials.

I've been able to test this by:
-commenting out all sections other than DHCP
-configure CIMSession to run on local system
-remove any references to remote PSSession
-retaining $ADSystem section, but not run against remote session.

### Before submitting

- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this feature request.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/issues) before submitting this feature request.

**Comment by rebelinux** [comment]
The primary intent of this report is to document Active Directory. The DHCP and DNS sections are considered optional services. Implementing a change as you recommend would be impossible to implement considering it would affect the original intent of the report.

**Comment by rebelinux** [comment]
Can you share with me the code you have already created?

I am considering adding this feature to the AsBuiltReport.Microsoft.Windows which is more focused on the standalone server.

https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.Windows

**Comment by dyde121** [comment]
Below is the quick and dirty modifications to Invoke-AsBuiltReport.Microsoft.AD.ps1 that I made on the fly to retrieve a DHCP report from all DHCP servers in the domain, without domain admin credentials.
(administrator permissions on indervidual DHCP servers required)

    $currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())

    if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {

        throw "The requested operation requires elevation: Run PowerShell console as administrator"
    }


    #Validate Required Modules and Features
    $OSType = (Get-ComputerInfo).OsProductType
    <#
    if ($OSType -eq 'WorkStation') {
        Get-RequiredFeature -Name 'Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0' -OSType $OSType
        Get-RequiredFeature -Name 'Rsat.CertificateServices.Tools~~~~0.0.1.0' -OSType $OSType
        Get-RequiredFeature -Name 'Rsat.GroupPolicy.Management.Tools~~~~0.0.1.0' -OSType $OSType
        Get-RequiredFeature -Name 'Rsat.Dns.Tools~~~~0.0.1.0' -OSType $OSType
        Get-RequiredFeature -Name 'Rsat.DHCP.Tools~~~~0.0.1.0' -OSType $OSType

    }
    if ($OSType -eq 'Server' -or $OSType -eq 'DomainController') {
        Get-RequiredFeature -Name RSAT-AD-PowerShell -OSType $OSType
        Get-RequiredFeature -Name RSAT-ADCS -OSType $OSType
        Get-RequiredFeature -Name RSAT-ADCS-mgmt -OSType $OSType
        Get-RequiredFeature -Name RSAT-DNS-Server -OSType $OSType
        Get-RequiredFeature -Name RSAT-DHCP -OSType $OSType
        Get-RequiredFeature -Name GPMC -OSType $OSType
    }
    #>

    #Get-RequiredModule -Name PSPKI -Version '3.7.2'


    # Import Report Configuration
    $Report = $ReportConfig.Report
    $InfoLevel = $ReportConfig.InfoLevel
    $Options = $ReportConfig.Options

    # Used to set values to TitleCase where required
    $TextInfo = (Get-Culture).TextInfo

    #---------------------------------------------------------------------------------------------#
    #                                 Connection Section                                          #
    #---------------------------------------------------------------------------------------------#
    <#
    foreach ($System in $Target) {
        Try {
            Write-PScriboMessage "Connecting to Domain Controller Server '$System'."
            $script:TempPssSession = New-PSSession $System -Credential $Credential -Authentication $Options.PSDefaultAuthentication -ErrorAction Stop
            $script:TempCIMSession = New-CIMSession $System -Credential $Credential -Authentication $Options.PSDefaultAuthentication -ErrorAction Stop
            $ADSystem = Invoke-Command -Session $TempPssSession { Get-ADForest -ErrorAction Stop}
        } Catch {
            throw "Unable to connect to the Domain Controller: $System"
        }
        $script:ForestInfo =  $ADSystem.RootDomain.toUpper()
        [array]$RootDomains = $ADSystem.RootDomain
        [array]$ChildDomains = $ADSystem.Domains | Where-Object {$_ -ne $RootDomains}
        [string]$OrderedDomains = $RootDomains + $ChildDomains
      #>
        $script:TempCIMSession = New-CIMSession -Credential $Credential -ErrorAction Stop
        $ADSystem = Get-ADForest -ErrorAction Stop
        $script:ForestInfo =  $ADSystem.RootDomain.toUpper()
        [array]$RootDomains = $ADSystem.RootDomain
        [array]$ChildDomains = $ADSystem.Domains | Where-Object {$_ -ne $RootDomains}
        [string]$OrderedDomains = $RootDomains + $ChildDomains

            #---------------------------------------------------------------------------------------------#
            #                                 DHCP Section                                                #
            #---------------------------------------------------------------------------------------------#
            if ($InfoLevel.DHCP -ge 1 -and (Get-DhcpServerInDC)) {
                Section -Style Heading2 "Dynamic Host Configuration Protocol Summary" {
                    if ($Options.ShowDefinitionInfo) {
                        Paragraph "The Dynamic Host Configuration Protocol (DHCP) is a network management protocol used on Internet Protocol (IP) networks for automatically assigning IP addresses and other communication parameters to devices connected to the network using a client/server architecture."
                        BlankLine
                    }
                    if (!$Options.ShowDefinitionInfo) {
                        Paragraph "The following section provides a summary of the Active Directory DHCP Infrastructure Information."
                        BlankLine
                    }
                    foreach ($Domain in ( $OrderedDomains.split(" "))) {
                        if ($Domain) {
                            if (($Domain -notin $Options.Exclude.Domains) -and (Get-ADDomain $Domain -ErrorAction Stop)) {
                                try {
                                    $DomainDHCPs = Get-DhcpServerInDC | Where-Object {$_.DnsName.split(".", 2)[1] -eq $Domain} | Select-Object -ExpandProperty DnsName | Where-Object {$_ -notin $Options.Exclude.DCs}
                                    if ($DomainDHCPs) {
                                        if ($Domain -eq $RootDomains) {
                                            $DomainHeading = "$($Domain.ToString().ToUpper()) Root Domain DHCP Configuration"
                                        } else {$DomainHeading = "$($Domain.ToString().ToUpper()) Child Domain DHCP Configuration"}
                                        Section -Style Heading3 $DomainHeading {
                                            Paragraph "The following section provides a summary of the Dynamic Host Configuration Protocol."
                                            BlankLine
                                            Get-AbrADDHCPInfrastructure -Domain $Domain
                                            Section -Style Heading4 "IPv4 Scope Configuration" {
                                                Paragraph "The following section provides a IPv4 configuration summary of the Dynamic Host Configuration Protocol."
                                                BlankLine
                                                try {
                                                    Get-AbrADDHCPv4Statistic -Domain $Domain
                                                }
                                                catch {
                                                    Write-PScriboMessage -IsWarning "Error: Retreiving DHCP Server IPv4 Statistics from  $($Domain.ToString().ToUpper())."
                                                    Write-PScriboMessage -IsWarning "$($_.Exception.Message) (IPv4 DHCP Server Statistics)"
                                                }
                                                foreach ($DHCPServer in $DomainDHCPs){
                                                    if (Test-Connection -ComputerName $DHCPServer -Quiet -Count 1) {
                                                        try {
                                                            Get-AbrADDHCPv4Scope -Domain $Domain -Server $DHCPServer
                                                        }
                                                        catch {
                                                            Write-PScriboMessage -IsWarning "$($_.Exception.Message) (IPv4 DHCP Server Scope information)"
                                                        }
                                                        if ($InfoLevel.DHCP -ge 2) {
                                                            try {
                                                                Get-AbrADDHCPv4ScopeServerSetting -Domain $Domain -Server $DHCPServer
                                                                $DHCPScopes =  Get-DhcpServerv4Scope -ComputerName $DHCPServer| Select-Object -ExpandProperty ScopeId
                                                                if ($DHCPScopes) {
                                                                    Section -Style Heading5 "Scope Options" {
                                                                        Paragraph "The following section provides a summary of the DHCP servers IPv4 Scope Server Options information."
                                                                        foreach ($Scope in $DHCPScopes) {
                                                                            try {
                                                                                Get-AbrADDHCPv4PerScopeSetting -Domain $Domain -Server $DHCPServer -Scope $Scope
                                                                            }
                                                                            catch {
                                                                                Write-PScriboMessage -IsWarning "Error: Retreiving DHCP Server IPv4 Scope configuration from $($DHCPServerr.split(".", 2)[0])."
                                                                                Write-PScriboMessage -IsWarning "$($_.Exception.Message) (IPv4 DHCP Server Scope configuration)"
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                            catch {
                                                                Write-PScriboMessage -IsWarning "$($_.Exception.Message) (IPv4 DHCP Scope Server Options)"
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                            Section -Style Heading4 "IPv6 Scope Configuration" {
                                                Paragraph "The following section provides a IPv6 configuration summary of the Dynamic Host Configuration Protocol."
                                                BlankLine
                                                try {
                                                    Get-AbrADDHCPv6Statistic -Domain $Domain
                                                }
                                                catch {
                                                    Write-PScriboMessage -IsWarning "Error: Retreiving DHCP Server IPv6 Statistics from $($Domain.ToString().ToUpper())."
                                                    Write-PScriboMessage -IsWarning "$($_.Exception.Message) (IPv6 DHCP Server IPv6 Statistics)"
                                                }
                                                foreach ($DHCPServer in $DomainDHCPs){
                                                    if (Test-Connection -ComputerName $DHCPServer -Quiet -Count 1) {
                                                        Write-PScriboMessage "Discovering Dhcp Server IPv6 Scopes from $DHCPServer"
                                                        try {
                                                            Get-AbrADDHCPv6Scope -Domain $Domain -Server $DHCPServer
                                                        }
                                                        catch {
                                                            Write-PscriboMessage -IsWarning "$($_.Exception.Message) (IPv6 DHCP Scope Information)"
                                                        }
                                                        if ($InfoLevel.DHCP -ge 2) {
                                                            try {
                                                                Get-AbrADDHCPv6ScopeServerSetting -Domain $Domain -Server $DHCPServer
                                                                $DHCPScopes =  Get-DhcpServerv6Scope -ComputerName $DHCPServer | Select-Object -ExpandProperty Prefix
                                                                if ($DHCPScopes) {
                                                                    Section -Style Heading5 "Scope Options" {
                                                                        Paragraph "The following section provides a summary 6 Scope Server Options information."
                                                                        BlankLine
                                                                        foreach ($Scope in $DHCPScopes) {
                                                                            try {
                                                                                Get-AbrADDHCPv6PerScopeSetting -Domain $Domain -Server $DHCPServer -Scope $Scope
                                                                            }
                                                                            catch {
                                                                                Write-PScriboMessage -IsWarning "Error: Retreiving DHCP Server IPv6 Scope configuration from $($DHCPServerr.split(".", 2)[0])."
                                                                                Write-PScriboMessage -IsWarning "$($_.Exception.Message) (IPv6 Per DHCP Scope configuration)"
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                            catch {
                                                                Write-PScriboMessage -IsWarning "$($_.Exception.Message) (IPv6 DHCP Scope Server Options)"
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                                catch {
                                    Write-PScriboMessage -IsWarning "$($_.Exception.Message) ($($Domain.ToString().ToUpper()) Domain DHCP Configuration)"
                                }
                            }
                        }
                    }
                }
            }
        #endregion AD Section
        #Write-PscriboMessage "Clearing PowerShell Session $($TempPssSession.Id)"
        #Remove-PSSession -Session $TempPssSession
        Write-PscriboMessage "Clearing CIM Session $($TempCIMSession.Id)"
        Remove-CIMSession -CimSession $TempCIMSession
	}#endregion foreach loop
`

**Comment by rebelinux** [comment]
I need more information to understand this request:

1. In that scenario the DHCP servers are part of the Domain so the discovery of the DHCP servers is done through the command "Get-DhcpServerInDC"? 

2. In that scenario the user does not have domain admin privileges but has physical or remote access through WIMRM/WINRS to the server so it is possible to get remote information?

**Comment by dyde121** [comment]
Correct to both.

The user may have these privileges either via “DHCP Administrators” AD group, or permissions on the individual DHCP servers.

**Comment by rebelinux** [comment]
Hello:

When you run the report with the code you send me, do you use a DHCP server as the target or a DC?

Best regards,

**Comment by dyde121** [comment]
Hey,

DHCP server as the target

**Comment by rebelinux** [comment]
A separate DHCP report will be created that includes the function you are requesting. I will be migrating DHCP, DNS and CA services in separate reports. I think this design makes more sense and will be easier to maintain each individual report.
