### ISSUE TITLE
Error while running the script

### ISSUE THREAD

**Issue by jpcapone** [AsBuiltReport/AsBuiltReport.Microsoft.AD#98]
### Bug description

While running any cmdlet to generate the AD report I get the error: `the server has returned the following error invalid enumeration context while running Get-Aduser`

### Command-line input

New-AsBuiltReport -Report Microsoft.AD -Target 'admin-dc-01v.contoso.local' -Username 'administrator@contoso.local' -Password 'P@ssw0rd' -Format Html,Word -OutputFolderPath 'C:\Users\Jon\Documents' -Timestamp

### Steps to reproduce

The error occurs after running `New-AsBuiltReport -Report Microsoft.AD -Target 'admin-dc-01v.contoso.local' -Username 'administrator@contoso.local' -Password 'P@ssw0rd' -Format Html,Word -OutputFolderPath 'C:\Users\Jon\Documents' -Timestamp`

### Expected behaviour

Script should run to completion with no errors.

### Operating System

Windows Server 2019

### PowerShell Version

5.1.22621.963 

### PowerShell Modules

```

Name                       Version
----                       -------
AsBuiltReport.Core         1.3.0  
AsBuiltReport.Microsoft.AD 0.7.12 
PScribo                    0.10.0 
PScriboCharts              0.9.0  
PSPKI                      3.7.2 
```

### Additional Context

The script does complete after the error occurs.  i believe it is caused by the number of users the` Get-ADUser `cmdlet has to parse 
which is roughly 265000 users.  I ran another script to validate the user object count and found that the difference in the value was neglible but very close.  

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this bug report.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/issues) before submitting this bug report.

**Comment by rebelinux** [comment]
Hello:

can you tell me which specific table in the report you are referring to?

thanks!

**Comment by jpcapone** [comment]
The Users Object Count Pie Chart and Table - 1.2.1.3.3.

**Comment by jpcapone** [comment]
heres a screenshot
![image](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/assets/47680328/d416917c-93c6-4fd0-96ca-c37a9bbe800a)

**Comment by jpcapone** [comment]
Heres a screenshot:
![image](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.AD/assets/47680328/2e655014-8aa5-4db9-ae91-25d4b9fa4131)

**Comment by rebelinux** [comment]
Thanks for the info,

could you share with me the other script you run to compare the numbers?

**Comment by jpcapone** [comment]
I kept it simple 
(Get-ADUser -Filter *).Count

**Comment by rebelinux** [comment]
I have done a test on a larger environment than yours and I can't reproduce the error. However, I made some changes in the code to see if it can help to avoid this type of error.

```
PS C:\Users\jocolon> (Get-ADUser -Filter *).Count
278838
PS C:\Users\jocolon> (Get-ADGroup -Filter *).Count
14693
```

Another question is if you executed the command with the EnableHealthCheck option?

**Comment by jpcapone** [comment]
I have gotten the error with and without the EnableHealthCheck option.  Its weird that you didn't get the same error.  If I update my module will the changes you made be downloaded?

**Comment by rebelinux** [comment]
I analyzed this situation in depth and was able to recreate the issue. I found that the error is caused when the powershell process consumes too much memory caused by the excessive amount of objects it has to process.

As much as I have improved the code I have not found a way through powershell to correct the error because most of the time it works but in certain occasions the error is displayed.

**Comment by jpcapone** [comment]
I greatly appreciate your efforts.  If you need someone to help test any changes please let me know.

**Comment by rebelinux** [comment]
> I greatly appreciate your efforts. If you need someone to help test any changes please let me know.

v0.7.13 is out with a lot of changes!

**Comment by rebelinux** [comment]
I updated PSPKI to version 4.0.0.0 with no problems. Additionally I ran the report with that version and didn't encounter any issues.

**Comment by jpcapone** [comment]
> I updated PSPKI to version 4.0.0.0 with no problems. Additionally I ran the report with that version and didn't encounter any issues.

I got the same certificate error when attempted to run the PSPKI update as well.  You didn't get that error for either?

**Comment by rebelinux** [comment]
When I did the update on one of my computers I did not get that error.

I have seen this error in other powershell modules and it is a known PowerShellGet issue.

https://github.com/PowerShell/PowerShellGetv2/issues/650

The use of the -SkipPublisherCheck parameter solves the problem.

However, I will modify the README file to include a comment on this possible issue. Thank you.

**Comment by rebelinux** [comment]
Any opinion on this matter?
